Feature/ Implement delete modal
JennyDoJD/javascript-training pull request #45
Opened 2024-06-03 09:25 UTC by JennyDoJD

2024-06-03 09:52 UTC, huyencao-agilityio commented on practice/src/index.html
> +          <div class="delete-model-content">
Typo `Model`

2024-06-04 01:37 UTC, canhpham-agilityio requested changes

2024-06-04 01:37 UTC, canhpham-agilityio commented on practice/src/index.html
> +                Save
@JennyDoJD It should be Yes or Ok

2024-06-04 01:37 UTC, canhpham-agilityio commented on practice/src/index.html
> +              <button class="btn btn-secondary btn-confirm" type="submit">
why should we need type="submit"?

2024-06-04 07:15 UTC, JennyDoJD commented on practice/src/index.html
> +              <button class="btn btn-secondary btn-confirm" type="submit">
it's the type="button"

2024-06-04 07:18 UTC, huyencao-agilityio approved these changes

2024-06-04 07:32 UTC, canhpham-agilityio approved these changes

2024-06-04 07:50 UTC, merged